export const smazat = 
        [{
            "url": "https://api.github.com/repos/angular/angular/issues/46938",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46938/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46938/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46938/events",
            "html_url": "https://github.com/angular/angular/issues/46938",
            "id": 1315052557,
            "node_id": "I_kwDOAXExC85OYhwN",
            "number": 46938,
            "title": "umd files missing in angular 14 - for loading angular with systemjs",
            "user": {
                "login": "damodharanj",
                "id": 8286067,
                "node_id": "MDQ6VXNlcjgyODYwNjc=",
                "avatar_url": "https://avatars.githubusercontent.com/u/8286067?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/damodharanj",
                "html_url": "https://github.com/damodharanj",
                "followers_url": "https://api.github.com/users/damodharanj/followers",
                "following_url": "https://api.github.com/users/damodharanj/following{/other_user}",
                "gists_url": "https://api.github.com/users/damodharanj/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/damodharanj/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/damodharanj/subscriptions",
                "organizations_url": "https://api.github.com/users/damodharanj/orgs",
                "repos_url": "https://api.github.com/users/damodharanj/repos",
                "events_url": "https://api.github.com/users/damodharanj/events{/privacy}",
                "received_events_url": "https://api.github.com/users/damodharanj/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": null,
            "comments": 0,
            "created_at": "2022-07-22T14:04:26Z",
            "updated_at": "2022-07-22T14:04:26Z",
            "closed_at": null,
            "author_association": "NONE",
            "active_lock_reason": null,
            "body": "### Which @angular/* package(s) are the source of the bug?\n\nDon't known / other\n\n### Is this a regression?\n\nNo\n\n### Description\n\nFor using angular using systemjs module loader, previously umd files were present in the following path\r\n\r\n@angular/core@14.0.0/fesm2015/core.mjs\r\n\r\nBut in Angular 14 the following path is not present. Where are recommended files present at ?\r\n\r\n\n\n### Please provide a link to a minimal reproduction of the bug\n\n_No response_\n\n### Please provide the exception or error you saw\n\n_No response_\n\n### Please provide the environment you discovered this bug in (run `ng version`)\n\n```true\n@angular/animations 14.0.0\r\n\r\n@angular/common 14.0.0\r\n\r\n@angular/compiler 14.0.0\r\n\r\n@angular/core 14.0.0\r\n\r\n@angular/forms 14.0.0\r\n\r\n@angular/platform-browser 14.0.0\r\n\r\n@angular/platform-browser-dynamic 14.0.0\r\n\r\n@angular/router 14.0.0\r\n\r\nrxjs 7.5.5\r\n\r\ntslib 2.4.0\r\n\r\nzone.js 0.11.5\n```\n\n\n### Anything else?\n\n_No response_",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46938/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46938/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        },

        {
            "url": "https://api.github.com/repos/angular/angular/issues/46935",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46935/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46935/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46935/events",
            "html_url": "https://github.com/angular/angular/issues/46935",
            "id": 1314618142,
            "node_id": "I_kwDOAXExC85OW3se",
            "number": 46935,
            "title": "asyncValidators trigger multiple times",
            "user": {
                "login": "binvb",
                "id": 18115907,
                "node_id": "MDQ6VXNlcjE4MTE1OTA3",
                "avatar_url": "https://avatars.githubusercontent.com/u/18115907?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/binvb",
                "html_url": "https://github.com/binvb",
                "followers_url": "https://api.github.com/users/binvb/followers",
                "following_url": "https://api.github.com/users/binvb/following{/other_user}",
                "gists_url": "https://api.github.com/users/binvb/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/binvb/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/binvb/subscriptions",
                "organizations_url": "https://api.github.com/users/binvb/orgs",
                "repos_url": "https://api.github.com/users/binvb/repos",
                "events_url": "https://api.github.com/users/binvb/events{/privacy}",
                "received_events_url": "https://api.github.com/users/binvb/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 393879365,
                    "node_id": "MDU6TGFiZWwzOTM4NzkzNjU=",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20forms",
                    "name": "comp: forms",
                    "color": "c5def5",
                    "default": false,
                    "description": null
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/83",
                "html_url": "https://github.com/angular/angular/milestone/83",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/83/labels",
                "id": 3143880,
                "node_id": "MDk6TWlsZXN0b25lMzE0Mzg4MA==",
                "number": 83,
                "title": "needsTriage",
                "description": "Milestone for all issues that haven't been triaged yet",
                "creator": {
                    "login": "ocombe",
                    "id": 265378,
                    "node_id": "MDQ6VXNlcjI2NTM3OA==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/265378?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/ocombe",
                    "html_url": "https://github.com/ocombe",
                    "followers_url": "https://api.github.com/users/ocombe/followers",
                    "following_url": "https://api.github.com/users/ocombe/following{/other_user}",
                    "gists_url": "https://api.github.com/users/ocombe/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/ocombe/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/ocombe/subscriptions",
                    "organizations_url": "https://api.github.com/users/ocombe/orgs",
                    "repos_url": "https://api.github.com/users/ocombe/repos",
                    "events_url": "https://api.github.com/users/ocombe/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/ocombe/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 121,
                "closed_issues": 7862,
                "state": "open",
                "created_at": "2018-02-26T14:22:18Z",
                "updated_at": "2022-07-22T08:54:43Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 0,
            "created_at": "2022-07-22T08:16:40Z",
            "updated_at": "2022-07-22T08:32:09Z",
            "closed_at": null,
            "author_association": "NONE",
            "active_lock_reason": null,
            "body": "### Which @angular/* package(s) are the source of the bug?\n\nforms\n\n### Is this a regression?\n\nNo\n\n### Description\n\nhey, guys\r\n  i was tryed to custom a form using async validators:\r\n```\r\n  ngOnInit(): void {\r\n    this.profileForm = new FormGroup({\r\n      firstName: new FormControl('',{\r\n        asyncValidators: this.validName\r\n      })\r\n    });\r\n  }\r\n  validName(ac: AbstractControl): Promise<ValidationErrors | null>{\r\n    return new Promise((resolve, reject) => {\r\n      console.log(`excuted async valid function: ${new Date().getTime()}`)\r\n      setTimeout(() => {\r\n        if(ac.value) {\r\n          resolve(null)\r\n        } else {\r\n          resolve({\r\n            errorMsg: 'name was duplicated!'\r\n          })\r\n        }\r\n\t  }, 2000)\r\n    })\r\n  }\r\n  get isValid() {\r\n\t\treturn this.profileForm.controls['firstName'].valid\r\n} \r\n```\r\nbut it trigger 3 times in init, thank you.\n\n### Please provide a link to a minimal reproduction of the bug\n\nhttps://codesandbox.io/s/thirsty-visvesvaraya-0ct6t9?file=/src/app/app.component.ts\n\n### Please provide the exception or error you saw\n\n```true\nexcuted async valid function: 1658472111853\r\nexcuted async valid function: 1658472111855\r\nexcuted async valid function: 1658472111856\n```\n\n\n### Please provide the environment you discovered this bug in (run `ng version`)\n\n```true\n@angular/cli@14.0.5  \r\nNode: v16.12.0  \r\n@angular/forms@14.0.5 \r\n@angular/core@14.0.5\n```\n\n\n### Anything else?\n\n_No response_",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46935/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46935/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        },
        {
            "url": "https://api.github.com/repos/angular/angular/issues/46933",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46933/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46933/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46933/events",
            "html_url": "https://github.com/angular/angular/issues/46933",
            "id": 1314522504,
            "node_id": "I_kwDOAXExC85OWgWI",
            "number": 46933,
            "title": "dynamic create component in library package not work",
            "user": {
                "login": "oudi",
                "id": 2518192,
                "node_id": "MDQ6VXNlcjI1MTgxOTI=",
                "avatar_url": "https://avatars.githubusercontent.com/u/2518192?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/oudi",
                "html_url": "https://github.com/oudi",
                "followers_url": "https://api.github.com/users/oudi/followers",
                "following_url": "https://api.github.com/users/oudi/following{/other_user}",
                "gists_url": "https://api.github.com/users/oudi/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/oudi/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/oudi/subscriptions",
                "organizations_url": "https://api.github.com/users/oudi/orgs",
                "repos_url": "https://api.github.com/users/oudi/repos",
                "events_url": "https://api.github.com/users/oudi/events{/privacy}",
                "received_events_url": "https://api.github.com/users/oudi/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 348933279,
                    "node_id": "MDU6TGFiZWwzNDg5MzMyNzk=",
                    "url": "https://api.github.com/repos/angular/angular/labels/needs%20reproduction",
                    "name": "needs reproduction",
                    "color": "000000",
                    "default": false,
                    "description": "This issue needs a reproduction in order for the team to investigate further"
                },
                {
                    "id": 1412404129,
                    "node_id": "MDU6TGFiZWwxNDEyNDA0MTI5",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20compiler",
                    "name": "comp: compiler",
                    "color": "c7def8",
                    "default": false,
                    "description": ""
                },
                {
                    "id": 3584695363,
                    "node_id": "LA_kwDOAXExC87VqhxD",
                    "url": "https://api.github.com/repos/angular/angular/labels/compiler:%20jit",
                    "name": "compiler: jit",
                    "color": "8ee24d",
                    "default": false,
                    "description": ""
                },
                {
                    "id": 3807561510,
                    "node_id": "MDU6TGFiZWwzODA3NTYxNTEw",
                    "url": "https://api.github.com/repos/angular/angular/labels/bug",
                    "name": "bug",
                    "color": "ee0701",
                    "default": true,
                    "description": null
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/82",
                "html_url": "https://github.com/angular/angular/milestone/82",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/82/labels",
                "id": 3045967,
                "node_id": "MDk6TWlsZXN0b25lMzA0NTk2Nw==",
                "number": 82,
                "title": "Backlog",
                "description": "Milestone for triaged issues that have not yet been scheduled for resolution.",
                "creator": {
                    "login": "IgorMinar",
                    "id": 216296,
                    "node_id": "MDQ6VXNlcjIxNjI5Ng==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/216296?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/IgorMinar",
                    "html_url": "https://github.com/IgorMinar",
                    "followers_url": "https://api.github.com/users/IgorMinar/followers",
                    "following_url": "https://api.github.com/users/IgorMinar/following{/other_user}",
                    "gists_url": "https://api.github.com/users/IgorMinar/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/IgorMinar/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/IgorMinar/subscriptions",
                    "organizations_url": "https://api.github.com/users/IgorMinar/orgs",
                    "repos_url": "https://api.github.com/users/IgorMinar/repos",
                    "events_url": "https://api.github.com/users/IgorMinar/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/IgorMinar/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 1023,
                "closed_issues": 9275,
                "state": "open",
                "created_at": "2018-01-18T16:52:20Z",
                "updated_at": "2022-07-22T13:45:20Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 5,
            "created_at": "2022-07-22T07:28:58Z",
            "updated_at": "2022-07-22T13:31:17Z",
            "closed_at": null,
            "author_association": "NONE",
            "active_lock_reason": null,
            "body": "### Which @angular/* package(s) are the source of the bug?\r\n\r\ncompiler, core\r\n\r\n### Is this a regression?\r\n\r\nNo\r\n\r\n### Description\r\n\r\nDynamic create a component and npm publish to a package. when using it in an angular app. it shows the error\r\n\r\n`Uncaught (in promise): Error: Unexpected value 'dynamicComponent' declared by the module 'class { }  '. Please add a @Pipe/@Directive/@Component annotation`\r\n\r\nIf I use it as a library project in the app. everything is ok.\r\n\r\n### Please provide a link to a minimal reproduction of the bug\r\n\r\n_No response_\r\n\r\n### Please provide the exception or error you saw\r\n\r\n```true\r\n         @Component({\r\n            selector: 'Component_' + pageState.PageID + '_' + pageState.PageState,\r\n            template: pageState.Template,\r\n            jit: true,\r\n          })\r\n          class dynamicComponent implements OnInit {\r\n\r\n            constructor() { }\r\n\r\n            ngOnInit() { }\r\n          };\r\n\r\n          @NgModule({\r\n            imports: dynamicDepens,\r\n            declarations: [dynamicComponent],\r\n            entryComponents: [dynamicComponent],\r\n            exports: [dynamicComponent],\r\n            jit: true,\r\n          })\r\n          class dynamicModule { };\r\n          const parent = this;\r\n          this.compiler.compileModuleAsync(dynamicModule).then(moduleFactory => {\r\n            const mod = moduleFactory.create(this.injector);\r\n            const componentFactory = mod.componentFactoryResolver.resolveComponentFactory(dynamicComponent);\r\n\r\n            const component = componentFactory.create(this.injector);\r\n            component.instance[\"parent\"] = parent.page.appID;\r\n            component.instance[\"splitterResizeStop\"] = function () {\r\n              parent.cdr.markForCheck();\r\n            };\r\n            this.contentTarget.insert(component.hostView);\r\n            this.cdr.markForCheck();\r\n          })\r\n        }).catch((error) => {\r\n          throw error;\r\n        })\r\n```\r\n\r\n```\r\ncore.js:4442 ERROR Error: Uncaught (in promise): Error: Unexpected value 'dynamicComponent' declared by the module 'class {\r\n                    }'. Please add a @Pipe/@Directive/@Component annotation.\r\nError: Unexpected value 'dynamicComponent' declared by the module 'class {\r\n                    }'. Please add a @Pipe/@Directive/@Component annotation.\r\n    at verifySemanticsOfNgModuleDef (core.js:25967:1)\r\n    at Function.get (core.js:25902:1)\r\n    at getInjectorDef (core.js:396:1)\r\n    at R3Injector.processInjectorType (core.js:11187:1)\r\n```\r\n```\r\n\r\n\r\n### Please provide the environment you discovered this bug in (run `ng version`)\r\n\r\n```true\r\nAngular CLI: 10.2.3\r\nNode: 16.15.0\r\nOS: win32 x64\r\n\r\nAngular: 10.2.5\r\n... animations, common, compiler, compiler-cli, core, forms\r\n... platform-browser, platform-browser-dynamic, router\r\nIvy Workspace: Yes\r\n```\r\n\r\n\r\n### Anything else?\r\n\r\n_No response_",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46933/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46933/timeline",
            "performed_via_github_app": null,
            "state_reason": "reopened"
        },
        {
            "url": "https://api.github.com/repos/angular/angular/issues/46932",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46932/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46932/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46932/events",
            "html_url": "https://github.com/angular/angular/pull/46932",
            "id": 1314038345,
            "node_id": "PR_kwDOAXExC8475YTw",
            "number": 46932,
            "title": "refactor(common): update error messages of NgOptimizedImage directive",
            "user": {
                "login": "AndrewKushnir",
                "id": 43554145,
                "node_id": "MDQ6VXNlcjQzNTU0MTQ1",
                "avatar_url": "https://avatars.githubusercontent.com/u/43554145?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/AndrewKushnir",
                "html_url": "https://github.com/AndrewKushnir",
                "followers_url": "https://api.github.com/users/AndrewKushnir/followers",
                "following_url": "https://api.github.com/users/AndrewKushnir/following{/other_user}",
                "gists_url": "https://api.github.com/users/AndrewKushnir/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/AndrewKushnir/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/AndrewKushnir/subscriptions",
                "organizations_url": "https://api.github.com/users/AndrewKushnir/orgs",
                "repos_url": "https://api.github.com/users/AndrewKushnir/repos",
                "events_url": "https://api.github.com/users/AndrewKushnir/events{/privacy}",
                "received_events_url": "https://api.github.com/users/AndrewKushnir/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 135584804,
                    "node_id": "MDU6TGFiZWwxMzU1ODQ4MDQ=",
                    "url": "https://api.github.com/repos/angular/angular/labels/action:%20cleanup",
                    "name": "action: cleanup",
                    "color": "e11d21",
                    "default": false,
                    "description": ""
                },
                {
                    "id": 217986512,
                    "node_id": "MDU6TGFiZWwyMTc5ODY1MTI=",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20common",
                    "name": "comp: common",
                    "color": "c7def8",
                    "default": false,
                    "description": null
                },
                {
                    "id": 2576265334,
                    "node_id": "MDU6TGFiZWwyNTc2MjY1MzM0",
                    "url": "https://api.github.com/repos/angular/angular/labels/PullApprove:%20disable",
                    "name": "PullApprove: disable",
                    "color": "5588cc",
                    "default": false,
                    "description": ""
                },
                {
                    "id": 4033536493,
                    "node_id": "LA_kwDOAXExC87wauHt",
                    "url": "https://api.github.com/repos/angular/angular/labels/target:%20feature",
                    "name": "target: feature",
                    "color": "5319e7",
                    "default": false,
                    "description": "This PR is targeted for a feature branch (outside of main and semver branches)"
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/82",
                "html_url": "https://github.com/angular/angular/milestone/82",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/82/labels",
                "id": 3045967,
                "node_id": "MDk6TWlsZXN0b25lMzA0NTk2Nw==",
                "number": 82,
                "title": "Backlog",
                "description": "Milestone for triaged issues that have not yet been scheduled for resolution.",
                "creator": {
                    "login": "IgorMinar",
                    "id": 216296,
                    "node_id": "MDQ6VXNlcjIxNjI5Ng==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/216296?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/IgorMinar",
                    "html_url": "https://github.com/IgorMinar",
                    "followers_url": "https://api.github.com/users/IgorMinar/followers",
                    "following_url": "https://api.github.com/users/IgorMinar/following{/other_user}",
                    "gists_url": "https://api.github.com/users/IgorMinar/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/IgorMinar/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/IgorMinar/subscriptions",
                    "organizations_url": "https://api.github.com/users/IgorMinar/orgs",
                    "repos_url": "https://api.github.com/users/IgorMinar/repos",
                    "events_url": "https://api.github.com/users/IgorMinar/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/IgorMinar/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 1023,
                "closed_issues": 9275,
                "state": "open",
                "created_at": "2018-01-18T16:52:20Z",
                "updated_at": "2022-07-22T13:45:20Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 1,
            "created_at": "2022-07-22T01:58:20Z",
            "updated_at": "2022-07-22T12:47:09Z",
            "closed_at": null,
            "author_association": "CONTRIBUTOR",
            "active_lock_reason": null,
            "draft": false,
            "pull_request": {
                "url": "https://api.github.com/repos/angular/angular/pulls/46932",
                "html_url": "https://github.com/angular/angular/pull/46932",
                "diff_url": "https://github.com/angular/angular/pull/46932.diff",
                "patch_url": "https://github.com/angular/angular/pull/46932.patch",
                "merged_at": null
            },
            "body": "This commit updates error messages that the NgOptimizedImage directive throws or logs into a console.\r\n\r\n## PR Type\r\nWhat kind of change does this PR introduce?\r\n\r\n- [x] Refactoring (no functional changes, no api changes)\r\n\r\n\r\n## Does this PR introduce a breaking change?\r\n\r\n- [ ] Yes\r\n- [x] No",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46932/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46932/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        },
        {
            "url": "https://api.github.com/repos/angular/angular/issues/46931",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46931/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46931/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46931/events",
            "html_url": "https://github.com/angular/angular/issues/46931",
            "id": 1313843011,
            "node_id": "I_kwDOAXExC85OT6dD",
            "number": 46931,
            "title": "Ampersand within embedded expressions causes HTML entities not to render",
            "user": {
                "login": "mcv203",
                "id": 109766913,
                "node_id": "U_kgDOBorpAQ",
                "avatar_url": "https://avatars.githubusercontent.com/u/109766913?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/mcv203",
                "html_url": "https://github.com/mcv203",
                "followers_url": "https://api.github.com/users/mcv203/followers",
                "following_url": "https://api.github.com/users/mcv203/following{/other_user}",
                "gists_url": "https://api.github.com/users/mcv203/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/mcv203/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/mcv203/subscriptions",
                "organizations_url": "https://api.github.com/users/mcv203/orgs",
                "repos_url": "https://api.github.com/users/mcv203/repos",
                "events_url": "https://api.github.com/users/mcv203/events{/privacy}",
                "received_events_url": "https://api.github.com/users/mcv203/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 375501288,
                    "node_id": "MDU6TGFiZWwzNzU1MDEyODg=",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20core",
                    "name": "comp: core",
                    "color": "c7def8",
                    "default": false,
                    "description": "Runtime issues"
                },
                {
                    "id": 1412404129,
                    "node_id": "MDU6TGFiZWwxNDEyNDA0MTI5",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20compiler",
                    "name": "comp: compiler",
                    "color": "c7def8",
                    "default": false,
                    "description": ""
                },
                {
                    "id": 1891815744,
                    "node_id": "MDU6TGFiZWwxODkxODE1NzQ0",
                    "url": "https://api.github.com/repos/angular/angular/labels/core:%20binding%20&%20interpolation",
                    "name": "core: binding & interpolation",
                    "color": "8ee24d",
                    "default": false,
                    "description": "Issue related to property/attribute binding or text interpolation"
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/83",
                "html_url": "https://github.com/angular/angular/milestone/83",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/83/labels",
                "id": 3143880,
                "node_id": "MDk6TWlsZXN0b25lMzE0Mzg4MA==",
                "number": 83,
                "title": "needsTriage",
                "description": "Milestone for all issues that haven't been triaged yet",
                "creator": {
                    "login": "ocombe",
                    "id": 265378,
                    "node_id": "MDQ6VXNlcjI2NTM3OA==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/265378?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/ocombe",
                    "html_url": "https://github.com/ocombe",
                    "followers_url": "https://api.github.com/users/ocombe/followers",
                    "following_url": "https://api.github.com/users/ocombe/following{/other_user}",
                    "gists_url": "https://api.github.com/users/ocombe/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/ocombe/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/ocombe/subscriptions",
                    "organizations_url": "https://api.github.com/users/ocombe/orgs",
                    "repos_url": "https://api.github.com/users/ocombe/repos",
                    "events_url": "https://api.github.com/users/ocombe/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/ocombe/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 121,
                "closed_issues": 7862,
                "state": "open",
                "created_at": "2018-02-26T14:22:18Z",
                "updated_at": "2022-07-22T08:54:43Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 2,
            "created_at": "2022-07-21T21:51:02Z",
            "updated_at": "2022-07-22T09:08:43Z",
            "closed_at": null,
            "author_association": "NONE",
            "active_lock_reason": null,
            "body": "### Which @angular/* package(s) are the source of the bug?\n\nDon't known / other\n\n### Is this a regression?\n\nYes\n\n### Description\n\nWhen an ampersand appears in an embedded expression, for example as part of a logical operator or literal, and the expression can evaluate to an HTML entity, that entity may not display properly.  E.g. <pre>{{(true && true) ? '&amp;ndash;' : '&amp;eacute;'}}</pre> results in the string \"&amp;ndash;\" being displayed.\r\n\r\nMore specifically, it appears that all characters from any ampersand to the subsequent semicolon are interpreted as if they are an entity regardless of placement, as can be seen in the reproduction:\r\n<pre>\r\n{{(true && true) ? '&amp;ndash;' : '&amp;eacute;'}} -> renders the string \"&amp;ndash;\"\r\n{{(true && ';') ? '&amp;ndash;' : '&amp;eacute;'}} -> renders &ndash; (an en dash)\r\n</pre>\r\n\r\nExamples in the reproduction follow:\r\n![image](https://user-images.githubusercontent.com/109766913/180320422-9c1a69c8-832c-46d2-90b6-ea8c1a2a330a.png)\r\n\r\nI recently upgraded from Angular 11 to 14 following the instructions.  I do not believe this existed in the earlier version, but suppose I can't be 100% positive of that.\n\n### Please provide a link to a minimal reproduction of the bug\n\nhttps://stackblitz.com/edit/angular-ivy-znh2ze\n\n### Please provide the exception or error you saw\n\n```true\nHTML entity renders as a string instead of the symbol.  No error is reported.\n```\n\n\n### Please provide the environment you discovered this bug in (run `ng version`)\n\n```true\nAngular CLI: 14.0.6\r\nNode: 14.15.1\r\nPackage Manager: npm 6.14.5\r\nOS: win32 x64\r\n\r\nAngular: 14.0.6\r\n... animations, cli, common, compiler, compiler-cli, core, forms\r\n... language-service, platform-browser, platform-browser-dynamic\r\n... platform-server, router\r\n\r\nPackage                         Version\r\n---------------------------------------------------------\r\n@angular-devkit/architect       0.1400.6\r\n@angular-devkit/build-angular   14.0.6\r\n@angular-devkit/core            14.0.6\r\n@angular-devkit/schematics      14.0.6\r\n@angular/cdk                    14.0.5\r\n@schematics/angular             14.0.6\r\nrxjs                            6.6.3\r\ntypescript                      4.7.4\n```\n\n\n### Anything else?\n\nThis is my first bug report, so let me know if I'm missing anything or if there's an easy way to know which package.  Thank you!",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46931/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46931/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        },
        {
            "url": "https://api.github.com/repos/angular/angular/issues/46930",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46930/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46930/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46930/events",
            "html_url": "https://github.com/angular/angular/issues/46930",
            "id": 1313723264,
            "node_id": "I_kwDOAXExC85OTdOA",
            "number": 46930,
            "title": "Support gzip in httpclient requests made on platform-server (with Universal)",
            "user": {
                "login": "amakhrov",
                "id": 1004015,
                "node_id": "MDQ6VXNlcjEwMDQwMTU=",
                "avatar_url": "https://avatars.githubusercontent.com/u/1004015?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/amakhrov",
                "html_url": "https://github.com/amakhrov",
                "followers_url": "https://api.github.com/users/amakhrov/followers",
                "following_url": "https://api.github.com/users/amakhrov/following{/other_user}",
                "gists_url": "https://api.github.com/users/amakhrov/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/amakhrov/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/amakhrov/subscriptions",
                "organizations_url": "https://api.github.com/users/amakhrov/orgs",
                "repos_url": "https://api.github.com/users/amakhrov/repos",
                "events_url": "https://api.github.com/users/amakhrov/events{/privacy}",
                "received_events_url": "https://api.github.com/users/amakhrov/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 535419697,
                    "node_id": "MDU6TGFiZWw1MzU0MTk2OTc=",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20server",
                    "name": "comp: server",
                    "color": "bfd4f2",
                    "default": false,
                    "description": null
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/83",
                "html_url": "https://github.com/angular/angular/milestone/83",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/83/labels",
                "id": 3143880,
                "node_id": "MDk6TWlsZXN0b25lMzE0Mzg4MA==",
                "number": 83,
                "title": "needsTriage",
                "description": "Milestone for all issues that haven't been triaged yet",
                "creator": {
                    "login": "ocombe",
                    "id": 265378,
                    "node_id": "MDQ6VXNlcjI2NTM3OA==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/265378?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/ocombe",
                    "html_url": "https://github.com/ocombe",
                    "followers_url": "https://api.github.com/users/ocombe/followers",
                    "following_url": "https://api.github.com/users/ocombe/following{/other_user}",
                    "gists_url": "https://api.github.com/users/ocombe/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/ocombe/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/ocombe/subscriptions",
                    "organizations_url": "https://api.github.com/users/ocombe/orgs",
                    "repos_url": "https://api.github.com/users/ocombe/repos",
                    "events_url": "https://api.github.com/users/ocombe/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/ocombe/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 121,
                "closed_issues": 7862,
                "state": "open",
                "created_at": "2018-02-26T14:22:18Z",
                "updated_at": "2022-07-22T08:54:43Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 0,
            "created_at": "2022-07-21T19:45:19Z",
            "updated_at": "2022-07-21T22:22:18Z",
            "closed_at": null,
            "author_association": "NONE",
            "active_lock_reason": null,
            "body": "### Which @angular/* package(s) are relevant/related to the feature request?\n\nplatform-server\n\n### Description\n\nHttpClient on platform-server uses `node-xhr2` under the hood. As such it doesn't support content compression (https://github.com/pwnall/node-xhr2/issues/17).\r\nWhile it might not be the greatest problem for requests made within the same datacenter (to our own apis), it impacts requests to external apis.\r\nAlso it negatively impacts local development experience (via `npm run dev:ssr`).\r\n\r\nThere is a related issue in the angular/universal repo - closed due to lack of support form the underlying node-xhr2 library. On the other hand, that library might never support it if no interest is expressed from the Angular team. Also the node-xhr2 author actually [mentioned](https://github.com/pwnall/node-xhr2/issues/17#issuecomment-415593037) they currently work on Google - which can make it easier to make a case for adding this feature.\n\n### Proposed solution\n\nImplement gzip support in the underlying `node-xhr2` library, update the dependency in Angular.\n\n### Alternatives considered\n\n- Roll our own implementation / fork of node-xhr\r\n- Use some other xhr-compatible node implementation (node-xhr2 doesn't seem to be actively maintained anyway)",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46930/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46930/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        },
        {
            "url": "https://api.github.com/repos/angular/angular/issues/46929",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46929/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46929/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46929/events",
            "html_url": "https://github.com/angular/angular/pull/46929",
            "id": 1313684795,
            "node_id": "PR_kwDOAXExC8474KFO",
            "number": 46929,
            "title": "refactor(common): provide value for `APP_BASE_HREF` by default",
            "user": {
                "login": "atscott",
                "id": 479713,
                "node_id": "MDQ6VXNlcjQ3OTcxMw==",
                "avatar_url": "https://avatars.githubusercontent.com/u/479713?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/atscott",
                "html_url": "https://github.com/atscott",
                "followers_url": "https://api.github.com/users/atscott/followers",
                "following_url": "https://api.github.com/users/atscott/following{/other_user}",
                "gists_url": "https://api.github.com/users/atscott/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/atscott/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/atscott/subscriptions",
                "organizations_url": "https://api.github.com/users/atscott/orgs",
                "repos_url": "https://api.github.com/users/atscott/repos",
                "events_url": "https://api.github.com/users/atscott/events{/privacy}",
                "received_events_url": "https://api.github.com/users/atscott/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 217986512,
                    "node_id": "MDU6TGFiZWwyMTc5ODY1MTI=",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20common",
                    "name": "comp: common",
                    "color": "c7def8",
                    "default": false,
                    "description": null
                },
                {
                    "id": 655699838,
                    "node_id": "MDU6TGFiZWw2NTU2OTk4Mzg=",
                    "url": "https://api.github.com/repos/angular/angular/labels/target:%20patch",
                    "name": "target: patch",
                    "color": "5319e7",
                    "default": false,
                    "description": "This PR is targeted for the next patch release"
                },
                {
                    "id": 4049110526,
                    "node_id": "LA_kwDOAXExC87xWIX-",
                    "url": "https://api.github.com/repos/angular/angular/labels/action:%20global%20presubmit",
                    "name": "action: global presubmit",
                    "color": "efa892",
                    "default": false,
                    "description": "A TGP is required and / or is running"
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/82",
                "html_url": "https://github.com/angular/angular/milestone/82",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/82/labels",
                "id": 3045967,
                "node_id": "MDk6TWlsZXN0b25lMzA0NTk2Nw==",
                "number": 82,
                "title": "Backlog",
                "description": "Milestone for triaged issues that have not yet been scheduled for resolution.",
                "creator": {
                    "login": "IgorMinar",
                    "id": 216296,
                    "node_id": "MDQ6VXNlcjIxNjI5Ng==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/216296?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/IgorMinar",
                    "html_url": "https://github.com/IgorMinar",
                    "followers_url": "https://api.github.com/users/IgorMinar/followers",
                    "following_url": "https://api.github.com/users/IgorMinar/following{/other_user}",
                    "gists_url": "https://api.github.com/users/IgorMinar/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/IgorMinar/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/IgorMinar/subscriptions",
                    "organizations_url": "https://api.github.com/users/IgorMinar/orgs",
                    "repos_url": "https://api.github.com/users/IgorMinar/repos",
                    "events_url": "https://api.github.com/users/IgorMinar/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/IgorMinar/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 1023,
                "closed_issues": 9275,
                "state": "open",
                "created_at": "2018-01-18T16:52:20Z",
                "updated_at": "2022-07-22T13:45:20Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 0,
            "created_at": "2022-07-21T19:09:01Z",
            "updated_at": "2022-07-21T20:18:19Z",
            "closed_at": null,
            "author_association": "CONTRIBUTOR",
            "active_lock_reason": null,
            "draft": true,
            "pull_request": {
                "url": "https://api.github.com/repos/angular/angular/pulls/46929",
                "html_url": "https://github.com/angular/angular/pull/46929",
                "diff_url": "https://github.com/angular/angular/pull/46929.diff",
                "patch_url": "https://github.com/angular/angular/pull/46929.patch",
                "merged_at": null
            },
            "body": "When using the Angular Router, one of `APP_BASE_HREF` or a `<base>` in\r\nthe header must be provided. When _not_ using the `RouterModule`,\r\ninjecting the `LocationStrategy` will result in the\r\n`PathLocationStrategy` being provided with a default value used in place\r\nof `APP_BASE_HREF` that is `document?.location?.origin ?? ''`.\r\n\r\nIt can be quite surprising and annoying that once you add `RouterModule`\r\nto the application, suddenly the `APP_BASE_HREF` must be specifically\r\nprovide something new when it could use a sensible default instead.\r\n\r\nThe current behavior (before this commit) is as follows:\r\n\r\n* When `RouterModule` is not provided (or the dev doesn't specifically provide\r\n  `PathLocationStrategy`): use `DOCUMENT.location?.origin ?? ''`.\r\n  Note that the base href in the dom and `APP_BASE_HREF` are not used.\r\n* When `RouterModule` _is_ provided:\r\n   1. APP_BASE_HREF if defined\r\n   2. Get base href from DOM\r\n   3. throw if neither of the two above are defined\r\n\r\nThis commit updates this behavior to be aligned regardless of `RouterModule`\r\nusage. The order (by default) is now:\r\n  1. Developer provided `APP_BASE_HREF`\r\n  2. base href from the DOM\r\n  3. `location.origin`\r\n  4. If none of the above exist, use `''`\r\n\r\nThis is slightly different than the behavior before. However, I believe\r\nit is more appropriate. For the case without `RouterModule`, it would\r\nlikely be surprising that `APP_BASE_HREF` and the base href from the DOM\r\nare ignored by default. For the case with `RouterModule`, we now have a\r\nmore sensible fallback/default when neither `APP_BASE_HREF` nor `<base>`\r\nare defined (instead of just throwing an error).\r\n",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46929/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46929/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        },
        {
            "url": "https://api.github.com/repos/angular/angular/issues/46928",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46928/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46928/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46928/events",
            "html_url": "https://github.com/angular/angular/issues/46928",
            "id": 1313629200,
            "node_id": "I_kwDOAXExC85OTGQQ",
            "number": 46928,
            "title": "False positive warnings about not animatable properties",
            "user": {
                "login": "dionatan-g",
                "id": 44219120,
                "node_id": "MDQ6VXNlcjQ0MjE5MTIw",
                "avatar_url": "https://avatars.githubusercontent.com/u/44219120?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/dionatan-g",
                "html_url": "https://github.com/dionatan-g",
                "followers_url": "https://api.github.com/users/dionatan-g/followers",
                "following_url": "https://api.github.com/users/dionatan-g/following{/other_user}",
                "gists_url": "https://api.github.com/users/dionatan-g/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/dionatan-g/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/dionatan-g/subscriptions",
                "organizations_url": "https://api.github.com/users/dionatan-g/orgs",
                "repos_url": "https://api.github.com/users/dionatan-g/repos",
                "events_url": "https://api.github.com/users/dionatan-g/events{/privacy}",
                "received_events_url": "https://api.github.com/users/dionatan-g/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 217956517,
                    "node_id": "MDU6TGFiZWwyMTc5NTY1MTc=",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20animations",
                    "name": "comp: animations",
                    "color": "c7def8",
                    "default": false,
                    "description": null
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/83",
                "html_url": "https://github.com/angular/angular/milestone/83",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/83/labels",
                "id": 3143880,
                "node_id": "MDk6TWlsZXN0b25lMzE0Mzg4MA==",
                "number": 83,
                "title": "needsTriage",
                "description": "Milestone for all issues that haven't been triaged yet",
                "creator": {
                    "login": "ocombe",
                    "id": 265378,
                    "node_id": "MDQ6VXNlcjI2NTM3OA==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/265378?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/ocombe",
                    "html_url": "https://github.com/ocombe",
                    "followers_url": "https://api.github.com/users/ocombe/followers",
                    "following_url": "https://api.github.com/users/ocombe/following{/other_user}",
                    "gists_url": "https://api.github.com/users/ocombe/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/ocombe/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/ocombe/subscriptions",
                    "organizations_url": "https://api.github.com/users/ocombe/orgs",
                    "repos_url": "https://api.github.com/users/ocombe/repos",
                    "events_url": "https://api.github.com/users/ocombe/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/ocombe/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 121,
                "closed_issues": 7862,
                "state": "open",
                "created_at": "2018-02-26T14:22:18Z",
                "updated_at": "2022-07-22T08:54:43Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 1,
            "created_at": "2022-07-21T18:15:08Z",
            "updated_at": "2022-07-22T07:21:02Z",
            "closed_at": null,
            "author_association": "NONE",
            "active_lock_reason": null,
            "body": "### Which @angular/* package(s) are the source of the bug?\r\n\r\nanimations\r\n\r\n### Is this a regression?\r\n\r\nNo\r\n\r\n### Description\r\n\r\nThere was already a fix for this warnings on #46666 but it didn't fix all the false positives.\r\n\r\nFor example with this code I get warnings.\r\n\r\n```\r\nexport const collapse: AnimationTriggerMetadata = trigger('collapseAnimation', [\r\n  state('expanded', style({ height: '*', visibility: 'visible' })),\r\n  state('hidden', style({ height: 0, overflow: 'hidden', borderTopWidth: '0', visibility: 'hidden' })),\r\n  transition('expanded => hidden', animate(`150ms ${AnimationCurves.EASE_IN_OUT}`)),\r\n  transition('hidden => expanded', animate(`150ms ${AnimationCurves.EASE_IN_OUT}`)),\r\n]);\r\n```\r\n\r\n```\r\n<div class=\"collapse-content\"\r\n     [class.collapse-content-active]=\"active\"\r\n     [@collapseAnimation]=\"active ? 'expanded' : 'hidden'\">\r\n  <div class=\"collapse-content-box\">\r\n    <ng-content></ng-content>\r\n  </div>\r\n</div>\r\n```\r\n\r\nFor me to remove the overflow hidden, I would have to set the style manually with the same delay as the animation.\r\n\r\n### Please provide a link to a minimal reproduction of the bug\r\n\r\n_No response_\r\n\r\n### Please provide the exception or error you saw\r\n\r\n```true\r\nWarning: The animation trigger \"collapseAnimation\" is attempting to animate the following not animatable properties: overflow\r\n(to check the list of all animatable properties visit https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_animated_properties)\r\n```\r\n\r\n\r\n### Please provide the environment you discovered this bug in (run `ng version`)\r\n\r\n```true\r\nAngular CLI: 14.0.4\r\nNode: 16.15.1\r\nPackage Manager: npm 8.13.2\r\nOS: win32 x64\r\n\r\nAngular: 14.0.4\r\n... cdk, cli, common, compiler, compiler-cli, core, forms\r\n... language-service, platform-browser, platform-browser-dynamic\r\n... router\r\n\r\nPackage                         Version\r\n---------------------------------------------------------\r\n@angular-devkit/architect       0.1400.4\r\n@angular-devkit/build-angular   14.0.4\r\n@angular-devkit/core            14.0.4\r\n@angular-devkit/schematics      14.0.4\r\n@angular/animations             14.0.6\r\n@schematics/angular             14.0.4\r\nng-packagr                      14.0.3\r\nrxjs                            7.5.5\r\ntypescript                      4.7.4\r\n```\r\n\r\n\r\n### Anything else?\r\n\r\n_No response_",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46928/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46928/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        },
        {
            "url": "https://api.github.com/repos/angular/angular/issues/46936",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46936/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46936/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46936/events",
            "html_url": "https://github.com/angular/angular/issues/46936",
            "id": 1314696445,
            "node_id": "I_kwDOAXExC85OXKz9",
            "number": 46936,
            "title": "propName.toLowerCase is not a function",
            "user": {
                "login": "Will-at-FreedomDev",
                "id": 59396813,
                "node_id": "MDQ6VXNlcjU5Mzk2ODEz",
                "avatar_url": "https://avatars.githubusercontent.com/u/59396813?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/Will-at-FreedomDev",
                "html_url": "https://github.com/Will-at-FreedomDev",
                "followers_url": "https://api.github.com/users/Will-at-FreedomDev/followers",
                "following_url": "https://api.github.com/users/Will-at-FreedomDev/following{/other_user}",
                "gists_url": "https://api.github.com/users/Will-at-FreedomDev/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/Will-at-FreedomDev/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/Will-at-FreedomDev/subscriptions",
                "organizations_url": "https://api.github.com/users/Will-at-FreedomDev/orgs",
                "repos_url": "https://api.github.com/users/Will-at-FreedomDev/repos",
                "events_url": "https://api.github.com/users/Will-at-FreedomDev/events{/privacy}",
                "received_events_url": "https://api.github.com/users/Will-at-FreedomDev/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 1412404129,
                    "node_id": "MDU6TGFiZWwxNDEyNDA0MTI5",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20compiler",
                    "name": "comp: compiler",
                    "color": "c7def8",
                    "default": false,
                    "description": ""
                },
                {
                    "id": 3807561510,
                    "node_id": "MDU6TGFiZWwzODA3NTYxNTEw",
                    "url": "https://api.github.com/repos/angular/angular/labels/bug",
                    "name": "bug",
                    "color": "ee0701",
                    "default": true,
                    "description": null
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/83",
                "html_url": "https://github.com/angular/angular/milestone/83",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/83/labels",
                "id": 3143880,
                "node_id": "MDk6TWlsZXN0b25lMzE0Mzg4MA==",
                "number": 83,
                "title": "needsTriage",
                "description": "Milestone for all issues that haven't been triaged yet",
                "creator": {
                    "login": "ocombe",
                    "id": 265378,
                    "node_id": "MDQ6VXNlcjI2NTM3OA==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/265378?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/ocombe",
                    "html_url": "https://github.com/ocombe",
                    "followers_url": "https://api.github.com/users/ocombe/followers",
                    "following_url": "https://api.github.com/users/ocombe/following{/other_user}",
                    "gists_url": "https://api.github.com/users/ocombe/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/ocombe/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/ocombe/subscriptions",
                    "organizations_url": "https://api.github.com/users/ocombe/orgs",
                    "repos_url": "https://api.github.com/users/ocombe/repos",
                    "events_url": "https://api.github.com/users/ocombe/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/ocombe/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 121,
                "closed_issues": 7862,
                "state": "open",
                "created_at": "2018-02-26T14:22:18Z",
                "updated_at": "2022-07-22T08:54:43Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 1,
            "created_at": "2022-07-21T18:09:52Z",
            "updated_at": "2022-07-22T13:03:21Z",
            "closed_at": null,
            "author_association": "NONE",
            "active_lock_reason": null,
            "body": "### Which @angular/* package(s) are the source of the bug?\r\n\r\ncompiler\r\n\r\n### Is this a regression?\r\n\r\nNo\r\n\r\n### Description\r\n\r\nI think I've narrowed down the reason for this error. I created an `@Input()` binding with the name `valueOf`. I think the angular compiler doesn't like this name for some reason, but I can't find any documentation on this being the case. I forked one of the Angular Material examples and updated the example a bit to demonstrate the error. \r\n\r\n```typescript\r\n@Component({\r\n  selector: 'app-value-of',\r\n  template: '{{valueOf(\"abc\")}}'\r\n})\r\nexport class ValueOfComponent {\r\n  @Input() valueOf: (s: string) => any = (s: string) => s;\r\n}\r\n\r\n@Component({\r\n  selector: 'autocomplete-filter-example',\r\n  template: '<app-value-of [valueOf]=\"myValueOf\"></app-value-of>',\r\n})\r\nexport class AutocompleteFilterExample {\r\n  myValueOf = (s: string) => 'something else';\r\n}\r\n```\r\n\r\n### Please provide a link to a minimal reproduction of the bug\r\n\r\nhttps://stackblitz.com/edit/angular-jyiqdv?file=src%2Fapp%2Fvalue-of.component.ts,src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fautocomplete-filter-example.ts,src%2Fapp%2Fautocomplete-filter-example.css,src%2Fapp%2Fautocomplete-filter-example.html\r\n\r\n### Please provide the exception or error you saw\r\n\r\n```true\r\n./src/main.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):\r\nError: propName.toLowerCase is not a function\r\n    at eval (/home/projects/angular-jyiqdv/node_modules/@ngtools/webpack/src/ivy/loader.js:81:18)\r\n\r\n./src/polyfills.ts - Error: Module build failed (from ./node_modules/@ngtools/webpack/src/ivy/index.js):\r\nError: propName.toLowerCase is not a function\r\n    at eval (/home/projects/angular-jyiqdv/node_modules/@ngtools/webpack/src/ivy/loader.js:81:18)\r\n```\r\n\r\n\r\n### Please provide the environment you discovered this bug in (run `ng version`)\r\n\r\n```true\r\nThis information can be found in the stackblitz reproduction. Looks like version 14.\r\n```\r\n\r\n\r\n### Anything else?\r\n\r\n_No response_",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46936/reactions",
                "total_count": 1,
                "+1": 1,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46936/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        },
        {
            "url": "https://api.github.com/repos/angular/angular/issues/46926",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46926/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46926/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46926/events",
            "html_url": "https://github.com/angular/angular/pull/46926",
            "id": 1313618196,
            "node_id": "PR_kwDOAXExC84737m5",
            "number": 46926,
            "title": "build: update dependency google-closure-compiler to v20220719",
            "user": {
                "login": "angular-robot",
                "id": 89942104,
                "node_id": "MDQ6VXNlcjg5OTQyMTA0",
                "avatar_url": "https://avatars.githubusercontent.com/u/89942104?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/angular-robot",
                "html_url": "https://github.com/angular-robot",
                "followers_url": "https://api.github.com/users/angular-robot/followers",
                "following_url": "https://api.github.com/users/angular-robot/following{/other_user}",
                "gists_url": "https://api.github.com/users/angular-robot/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/angular-robot/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/angular-robot/subscriptions",
                "organizations_url": "https://api.github.com/users/angular-robot/orgs",
                "repos_url": "https://api.github.com/users/angular-robot/repos",
                "events_url": "https://api.github.com/users/angular-robot/events{/privacy}",
                "received_events_url": "https://api.github.com/users/angular-robot/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 193817683,
                    "node_id": "MDU6TGFiZWwxOTM4MTc2ODM=",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20build%20&%20ci",
                    "name": "comp: build & ci",
                    "color": "c7def8",
                    "default": false,
                    "description": "Issue related to the Angular team's *own* build/CI tooling"
                },
                {
                    "id": 217969169,
                    "node_id": "MDU6TGFiZWwyMTc5NjkxNjk=",
                    "url": "https://api.github.com/repos/angular/angular/labels/action:%20review",
                    "name": "action: review",
                    "color": "fbca04",
                    "default": false,
                    "description": ""
                },
                {
                    "id": 655699838,
                    "node_id": "MDU6TGFiZWw2NTU2OTk4Mzg=",
                    "url": "https://api.github.com/repos/angular/angular/labels/target:%20patch",
                    "name": "target: patch",
                    "color": "5319e7",
                    "default": false,
                    "description": "This PR is targeted for the next patch release"
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/82",
                "html_url": "https://github.com/angular/angular/milestone/82",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/82/labels",
                "id": 3045967,
                "node_id": "MDk6TWlsZXN0b25lMzA0NTk2Nw==",
                "number": 82,
                "title": "Backlog",
                "description": "Milestone for triaged issues that have not yet been scheduled for resolution.",
                "creator": {
                    "login": "IgorMinar",
                    "id": 216296,
                    "node_id": "MDQ6VXNlcjIxNjI5Ng==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/216296?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/IgorMinar",
                    "html_url": "https://github.com/IgorMinar",
                    "followers_url": "https://api.github.com/users/IgorMinar/followers",
                    "following_url": "https://api.github.com/users/IgorMinar/following{/other_user}",
                    "gists_url": "https://api.github.com/users/IgorMinar/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/IgorMinar/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/IgorMinar/subscriptions",
                    "organizations_url": "https://api.github.com/users/IgorMinar/orgs",
                    "repos_url": "https://api.github.com/users/IgorMinar/repos",
                    "events_url": "https://api.github.com/users/IgorMinar/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/IgorMinar/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 1023,
                "closed_issues": 9275,
                "state": "open",
                "created_at": "2018-01-18T16:52:20Z",
                "updated_at": "2022-07-22T13:45:20Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 0,
            "created_at": "2022-07-21T18:04:57Z",
            "updated_at": "2022-07-22T02:08:38Z",
            "closed_at": null,
            "author_association": "COLLABORATOR",
            "active_lock_reason": null,
            "draft": false,
            "pull_request": {
                "url": "https://api.github.com/repos/angular/angular/pulls/46926",
                "html_url": "https://github.com/angular/angular/pull/46926",
                "diff_url": "https://github.com/angular/angular/pull/46926.diff",
                "patch_url": "https://github.com/angular/angular/pull/46926.patch",
                "merged_at": null
            },
            "body": "This PR contains the following updates:\n\n| Package | Type | Update | Change |\n|---|---|---|---|\n| [google-closure-compiler](https://developers.google.com/closure/compiler/) ([source](https://togithub.com/google/closure-compiler-npm)) | devDependencies | major | [`^20220601.0.0` -> `^20220719.0.0`](https://renovatebot.com/diffs/npm/google-closure-compiler/20220601.0.0/20220719.0.0) |\n| [google-closure-compiler](https://developers.google.com/closure/compiler/) ([source](https://togithub.com/google/closure-compiler-npm)) | dependencies | major | [`20220601.0.0` -> `20220719.0.0`](https://renovatebot.com/diffs/npm/google-closure-compiler/20220601.0.0/20220719.0.0) |\n\n---\n\n### Release Notes\n\n<details>\n<summary>google/closure-compiler-npm</summary>\n\n### [`v20220719.0.0`](https://togithub.com/google/closure-compiler-npm/compare/v20220601.0.0...v20220719.0.0)\n\n[Compare Source](https://togithub.com/google/closure-compiler-npm/compare/v20220601.0.0...v20220719.0.0)\n\n</details>\n\n---\n\n### Configuration\n\n📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).\n\n🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.\n\n♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.\n\n🔕 **Ignore**: Close this PR and you won't be reminded about these updates again.\n\n---\n\n - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, click this checkbox.\n\n---\n\nThis PR has been generated by [Renovate Bot](https://togithub.com/renovatebot/renovate).\n<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzMi4xMjAuMCIsInVwZGF0ZWRJblZlciI6IjMyLjEyMC4wIn0=-->\n",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46926/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46926/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        },
        {
            "url": "https://api.github.com/repos/angular/angular/issues/46924",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46924/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46924/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46924/events",
            "html_url": "https://github.com/angular/angular/pull/46924",
            "id": 1313503372,
            "node_id": "PR_kwDOAXExC8473isy",
            "number": 46924,
            "title": "refactor(router): Move bootstrapDone usage next to where it's required",
            "user": {
                "login": "atscott",
                "id": 479713,
                "node_id": "MDQ6VXNlcjQ3OTcxMw==",
                "avatar_url": "https://avatars.githubusercontent.com/u/479713?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/atscott",
                "html_url": "https://github.com/atscott",
                "followers_url": "https://api.github.com/users/atscott/followers",
                "following_url": "https://api.github.com/users/atscott/following{/other_user}",
                "gists_url": "https://api.github.com/users/atscott/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/atscott/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/atscott/subscriptions",
                "organizations_url": "https://api.github.com/users/atscott/orgs",
                "repos_url": "https://api.github.com/users/atscott/repos",
                "events_url": "https://api.github.com/users/atscott/events{/privacy}",
                "received_events_url": "https://api.github.com/users/atscott/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 217962760,
                    "node_id": "MDU6TGFiZWwyMTc5NjI3NjA=",
                    "url": "https://api.github.com/repos/angular/angular/labels/state:%20blocked",
                    "name": "state: blocked",
                    "color": "e11d21",
                    "default": false,
                    "description": ""
                },
                {
                    "id": 218430644,
                    "node_id": "MDU6TGFiZWwyMTg0MzA2NDQ=",
                    "url": "https://api.github.com/repos/angular/angular/labels/refactoring",
                    "name": "refactoring",
                    "color": "d4c5f9",
                    "default": false,
                    "description": "Issue that involves refactoring or code-cleanup"
                },
                {
                    "id": 375500771,
                    "node_id": "MDU6TGFiZWwzNzU1MDA3NzE=",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20router",
                    "name": "comp: router",
                    "color": "c7def8",
                    "default": false,
                    "description": null
                },
                {
                    "id": 655699838,
                    "node_id": "MDU6TGFiZWw2NTU2OTk4Mzg=",
                    "url": "https://api.github.com/repos/angular/angular/labels/target:%20patch",
                    "name": "target: patch",
                    "color": "5319e7",
                    "default": false,
                    "description": "This PR is targeted for the next patch release"
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/82",
                "html_url": "https://github.com/angular/angular/milestone/82",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/82/labels",
                "id": 3045967,
                "node_id": "MDk6TWlsZXN0b25lMzA0NTk2Nw==",
                "number": 82,
                "title": "Backlog",
                "description": "Milestone for triaged issues that have not yet been scheduled for resolution.",
                "creator": {
                    "login": "IgorMinar",
                    "id": 216296,
                    "node_id": "MDQ6VXNlcjIxNjI5Ng==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/216296?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/IgorMinar",
                    "html_url": "https://github.com/IgorMinar",
                    "followers_url": "https://api.github.com/users/IgorMinar/followers",
                    "following_url": "https://api.github.com/users/IgorMinar/following{/other_user}",
                    "gists_url": "https://api.github.com/users/IgorMinar/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/IgorMinar/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/IgorMinar/subscriptions",
                    "organizations_url": "https://api.github.com/users/IgorMinar/orgs",
                    "repos_url": "https://api.github.com/users/IgorMinar/repos",
                    "events_url": "https://api.github.com/users/IgorMinar/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/IgorMinar/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 1023,
                "closed_issues": 9275,
                "state": "open",
                "created_at": "2018-01-18T16:52:20Z",
                "updated_at": "2022-07-22T13:45:20Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 1,
            "created_at": "2022-07-21T16:17:56Z",
            "updated_at": "2022-07-21T20:06:25Z",
            "closed_at": null,
            "author_association": "CONTRIBUTOR",
            "active_lock_reason": null,
            "draft": false,
            "pull_request": {
                "url": "https://api.github.com/repos/angular/angular/pulls/46924",
                "html_url": "https://github.com/angular/angular/pull/46924",
                "diff_url": "https://github.com/angular/angular/pull/46924.diff",
                "patch_url": "https://github.com/angular/angular/pull/46924.patch",
                "merged_at": null
            },
            "body": "The BOOTSTRAP_DONE/bootstrapDone Subject is only used as part of the\r\n`enabledBlocking` initial navigation. Rather than completing the subject\r\nin a common bootstrap listener, this logic can be done in its own\r\nlistener as part of the `provideEnabledBlockingInitialNavigation`\r\nfunction.",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46924/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46924/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        },
        {
            "url": "https://api.github.com/repos/angular/angular/issues/46923",
            "repository_url": "https://api.github.com/repos/angular/angular",
            "labels_url": "https://api.github.com/repos/angular/angular/issues/46923/labels{/name}",
            "comments_url": "https://api.github.com/repos/angular/angular/issues/46923/comments",
            "events_url": "https://api.github.com/repos/angular/angular/issues/46923/events",
            "html_url": "https://github.com/angular/angular/pull/46923",
            "id": 1313499719,
            "node_id": "PR_kwDOAXExC8473h66",
            "number": 46923,
            "title": "refactor(router): Remove providePathLocationStrategy helper",
            "user": {
                "login": "atscott",
                "id": 479713,
                "node_id": "MDQ6VXNlcjQ3OTcxMw==",
                "avatar_url": "https://avatars.githubusercontent.com/u/479713?v=4",
                "gravatar_id": "",
                "url": "https://api.github.com/users/atscott",
                "html_url": "https://github.com/atscott",
                "followers_url": "https://api.github.com/users/atscott/followers",
                "following_url": "https://api.github.com/users/atscott/following{/other_user}",
                "gists_url": "https://api.github.com/users/atscott/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/atscott/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/atscott/subscriptions",
                "organizations_url": "https://api.github.com/users/atscott/orgs",
                "repos_url": "https://api.github.com/users/atscott/repos",
                "events_url": "https://api.github.com/users/atscott/events{/privacy}",
                "received_events_url": "https://api.github.com/users/atscott/received_events",
                "type": "User",
                "site_admin": false
            },
            "labels": [
                {
                    "id": 217962760,
                    "node_id": "MDU6TGFiZWwyMTc5NjI3NjA=",
                    "url": "https://api.github.com/repos/angular/angular/labels/state:%20blocked",
                    "name": "state: blocked",
                    "color": "e11d21",
                    "default": false,
                    "description": ""
                },
                {
                    "id": 375500771,
                    "node_id": "MDU6TGFiZWwzNzU1MDA3NzE=",
                    "url": "https://api.github.com/repos/angular/angular/labels/comp:%20router",
                    "name": "comp: router",
                    "color": "c7def8",
                    "default": false,
                    "description": null
                },
                {
                    "id": 655699838,
                    "node_id": "MDU6TGFiZWw2NTU2OTk4Mzg=",
                    "url": "https://api.github.com/repos/angular/angular/labels/target:%20patch",
                    "name": "target: patch",
                    "color": "5319e7",
                    "default": false,
                    "description": "This PR is targeted for the next patch release"
                },
                {
                    "id": 4049110526,
                    "node_id": "LA_kwDOAXExC87xWIX-",
                    "url": "https://api.github.com/repos/angular/angular/labels/action:%20global%20presubmit",
                    "name": "action: global presubmit",
                    "color": "efa892",
                    "default": false,
                    "description": "A TGP is required and / or is running"
                }
            ],
            "state": "open",
            "locked": false,
            "assignee": null,
            "assignees": [],
            "milestone": {
                "url": "https://api.github.com/repos/angular/angular/milestones/82",
                "html_url": "https://github.com/angular/angular/milestone/82",
                "labels_url": "https://api.github.com/repos/angular/angular/milestones/82/labels",
                "id": 3045967,
                "node_id": "MDk6TWlsZXN0b25lMzA0NTk2Nw==",
                "number": 82,
                "title": "Backlog",
                "description": "Milestone for triaged issues that have not yet been scheduled for resolution.",
                "creator": {
                    "login": "IgorMinar",
                    "id": 216296,
                    "node_id": "MDQ6VXNlcjIxNjI5Ng==",
                    "avatar_url": "https://avatars.githubusercontent.com/u/216296?v=4",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/IgorMinar",
                    "html_url": "https://github.com/IgorMinar",
                    "followers_url": "https://api.github.com/users/IgorMinar/followers",
                    "following_url": "https://api.github.com/users/IgorMinar/following{/other_user}",
                    "gists_url": "https://api.github.com/users/IgorMinar/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/IgorMinar/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/IgorMinar/subscriptions",
                    "organizations_url": "https://api.github.com/users/IgorMinar/orgs",
                    "repos_url": "https://api.github.com/users/IgorMinar/repos",
                    "events_url": "https://api.github.com/users/IgorMinar/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/IgorMinar/received_events",
                    "type": "User",
                    "site_admin": false
                },
                "open_issues": 1023,
                "closed_issues": 9275,
                "state": "open",
                "created_at": "2018-01-18T16:52:20Z",
                "updated_at": "2022-07-22T13:45:20Z",
                "due_on": null,
                "closed_at": null
            },
            "comments": 1,
            "created_at": "2022-07-21T16:14:47Z",
            "updated_at": "2022-07-21T19:20:31Z",
            "closed_at": null,
            "author_association": "CONTRIBUTOR",
            "active_lock_reason": null,
            "draft": false,
            "pull_request": {
                "url": "https://api.github.com/repos/angular/angular/pulls/46923",
                "html_url": "https://github.com/angular/angular/pull/46923",
                "diff_url": "https://github.com/angular/angular/pull/46923.diff",
                "patch_url": "https://github.com/angular/angular/pull/46923.patch",
                "merged_at": null
            },
            "body": "The PathLocationStrategy is already provided by default in the factory of LocationStrategy\r\n",
            "reactions": {
                "url": "https://api.github.com/repos/angular/angular/issues/46923/reactions",
                "total_count": 0,
                "+1": 0,
                "-1": 0,
                "laugh": 0,
                "hooray": 0,
                "confused": 0,
                "heart": 0,
                "rocket": 0,
                "eyes": 0
            },
            "timeline_url": "https://api.github.com/repos/angular/angular/issues/46923/timeline",
            "performed_via_github_app": null,
            "state_reason": null
        }]