export const smazat = {
        "url": "https://api.github.com/repos/angular/angular/issues/42011",
        "repository_url": "https://api.github.com/repos/angular/angular",
        "labels_url": "https://api.github.com/repos/angular/angular/issues/42011/labels{/name}",
        "comments_url": "https://api.github.com/repos/angular/angular/issues/42011/comments",
        "events_url": "https://api.github.com/repos/angular/angular/issues/42011/events",
        "html_url": "https://github.com/angular/angular/issues/42011",
        "id": 882096418,
        "node_id": "MDU6SXNzdWU4ODIwOTY0MTg=",
        "number": 42011,
        "title": "Support Typescript incremental build",
        "user": {
          "login": "glebmachine",
          "id": 1610882,
          "node_id": "MDQ6VXNlcjE2MTA4ODI=",
          "avatar_url": "https://avatars.githubusercontent.com/u/1610882?v=4",
          "gravatar_id": "",
          "url": "https://api.github.com/users/glebmachine",
          "html_url": "https://github.com/glebmachine",
          "followers_url": "https://api.github.com/users/glebmachine/followers",
          "following_url": "https://api.github.com/users/glebmachine/following{/other_user}",
          "gists_url": "https://api.github.com/users/glebmachine/gists{/gist_id}",
          "starred_url": "https://api.github.com/users/glebmachine/starred{/owner}{/repo}",
          "subscriptions_url": "https://api.github.com/users/glebmachine/subscriptions",
          "organizations_url": "https://api.github.com/users/glebmachine/orgs",
          "repos_url": "https://api.github.com/users/glebmachine/repos",
          "events_url": "https://api.github.com/users/glebmachine/events{/privacy}",
          "received_events_url": "https://api.github.com/users/glebmachine/received_events",
          "type": "User",
          "site_admin": false
        },
        "labels": [
          {
            "id": 130606845,
            "node_id": "MDU6TGFiZWwxMzA2MDY4NDU=",
            "url": "https://api.github.com/repos/angular/angular/labels/feature",
            "name": "feature",
            "color": "7028c1",
            "default": false,
            "description": "Issue that requests a new feature"
          },
          {
            "id": 1412404129,
            "node_id": "MDU6TGFiZWwxNDEyNDA0MTI5",
            "url": "https://api.github.com/repos/angular/angular/labels/comp:%20compiler",
            "name": "comp: compiler",
            "color": "c7def8",
            "default": false,
            "description": ""
          },
          {
            "id": 3020552131,
            "node_id": "MDU6TGFiZWwzMDIwNTUyMTMx",
            "url": "https://api.github.com/repos/angular/angular/labels/under%20consideration",
            "name": "under consideration",
            "color": "840EFD",
            "default": false,
            "description": ""
          }
        ],
        "state": "open",
        "locked": false,
        "assignee": null,
        "assignees": [
      
        ],
        "milestone": {
          "url": "https://api.github.com/repos/angular/angular/milestones/82",
          "html_url": "https://github.com/angular/angular/milestone/82",
          "labels_url": "https://api.github.com/repos/angular/angular/milestones/82/labels",
          "id": 3045967,
          "node_id": "MDk6TWlsZXN0b25lMzA0NTk2Nw==",
          "number": 82,
          "title": "Backlog",
          "description": "Milestone for triaged issues that have not yet been scheduled for resolution.",
          "creator": {
            "login": "IgorMinar",
            "id": 216296,
            "node_id": "MDQ6VXNlcjIxNjI5Ng==",
            "avatar_url": "https://avatars.githubusercontent.com/u/216296?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/IgorMinar",
            "html_url": "https://github.com/IgorMinar",
            "followers_url": "https://api.github.com/users/IgorMinar/followers",
            "following_url": "https://api.github.com/users/IgorMinar/following{/other_user}",
            "gists_url": "https://api.github.com/users/IgorMinar/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/IgorMinar/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/IgorMinar/subscriptions",
            "organizations_url": "https://api.github.com/users/IgorMinar/orgs",
            "repos_url": "https://api.github.com/users/IgorMinar/repos",
            "events_url": "https://api.github.com/users/IgorMinar/events{/privacy}",
            "received_events_url": "https://api.github.com/users/IgorMinar/received_events",
            "type": "User",
            "site_admin": false
          },
          "open_issues": 1031,
          "closed_issues": 9283,
          "state": "open",
          "created_at": "2018-01-18T16:52:20Z",
          "updated_at": "2022-07-26T11:29:49Z",
          "due_on": null,
          "closed_at": null
        },
        "comments": 52,
        "created_at": "2019-03-18T16:03:13Z",
        "updated_at": "2021-07-08T23:58:29Z",
        "closed_at": null,
        "author_association": "NONE",
        "active_lock_reason": null,
        "body": "<!--🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅\r\n\r\nOh hi there! 😄\r\n\r\nTo expedite issue processing please search open and closed issues before submitting a new one.\r\nExisting issues often contain information about workarounds, resolution, or progress updates.\r\n\r\n🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅🔅-->\r\n\r\n\r\n# 🚀 Feature request\r\n```\r\n- [ ] new\r\n- [x] build\r\n- [x] serve\r\n- [x] test\r\n- [x] e2e\r\n- [ ] generate\r\n- [ ] add\r\n- [ ] update\r\n- [ ] lint\r\n- [ ] xi18n\r\n- [ ] run\r\n- [ ] config\r\n- [ ] help\r\n- [ ] version\r\n- [ ] doc\r\n```\r\n\r\n### Description\r\nSupport of Typescript incremental build https://devblogs.microsoft.com/typescript/announcing-typescript-3-4-rc/",
        "closed_by": null,
        "reactions": {
          "url": "https://api.github.com/repos/angular/angular/issues/42011/reactions",
          "total_count": 129,
          "+1": 104,
          "-1": 0,
          "laugh": 0,
          "hooray": 0,
          "confused": 0,
          "heart": 12,
          "rocket": 13,
          "eyes": 0
        },
        "timeline_url": "https://api.github.com/repos/angular/angular/issues/42011/timeline",
        "performed_via_github_app": null,
        "state_reason": null
      }
      //////////////////////////
      ////////Komentáře////////
      ////////////////////////
      export const smazatComments = 
      [
        {
          "id": 39704110,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb24zOTcwNDExMA==",
          "user": {
            "login": "Cselt",
            "id": 11027521,
            "node_id": "MDQ6VXNlcjExMDI3NTIx",
            "avatar_url": "https://avatars.githubusercontent.com/u/11027521?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Cselt",
            "html_url": "https://github.com/Cselt",
            "followers_url": "https://api.github.com/users/Cselt/followers",
            "following_url": "https://api.github.com/users/Cselt/following{/other_user}",
            "gists_url": "https://api.github.com/users/Cselt/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Cselt/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Cselt/subscriptions",
            "organizations_url": "https://api.github.com/users/Cselt/orgs",
            "repos_url": "https://api.github.com/users/Cselt/repos",
            "events_url": "https://api.github.com/users/Cselt/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Cselt/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-03-28T13:37:32Z"
        },
        {
          "id": 39990147,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb24zOTk5MDE0Nw==",
          "user": {
            "login": "jdpnielsen",
            "id": 8746698,
            "node_id": "MDQ6VXNlcjg3NDY2OTg=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8746698?u=cea5c8df39ef7716b2df7ef47dd6bf45a18c399e&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jdpnielsen",
            "html_url": "https://github.com/jdpnielsen",
            "followers_url": "https://api.github.com/users/jdpnielsen/followers",
            "following_url": "https://api.github.com/users/jdpnielsen/following{/other_user}",
            "gists_url": "https://api.github.com/users/jdpnielsen/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jdpnielsen/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jdpnielsen/subscriptions",
            "organizations_url": "https://api.github.com/users/jdpnielsen/orgs",
            "repos_url": "https://api.github.com/users/jdpnielsen/repos",
            "events_url": "https://api.github.com/users/jdpnielsen/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jdpnielsen/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-02T12:05:26Z"
        },
        {
          "id": 40039144,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDAzOTE0NA==",
          "user": {
            "login": "benneq",
            "id": 1627305,
            "node_id": "MDQ6VXNlcjE2MjczMDU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1627305?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/benneq",
            "html_url": "https://github.com/benneq",
            "followers_url": "https://api.github.com/users/benneq/followers",
            "following_url": "https://api.github.com/users/benneq/following{/other_user}",
            "gists_url": "https://api.github.com/users/benneq/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/benneq/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/benneq/subscriptions",
            "organizations_url": "https://api.github.com/users/benneq/orgs",
            "repos_url": "https://api.github.com/users/benneq/repos",
            "events_url": "https://api.github.com/users/benneq/events{/privacy}",
            "received_events_url": "https://api.github.com/users/benneq/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-02T23:24:11Z"
        },
        {
          "id": 40090600,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDA5MDYwMA==",
          "user": {
            "login": "larrifax",
            "id": 144189,
            "node_id": "MDQ6VXNlcjE0NDE4OQ==",
            "avatar_url": "https://avatars.githubusercontent.com/u/144189?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/larrifax",
            "html_url": "https://github.com/larrifax",
            "followers_url": "https://api.github.com/users/larrifax/followers",
            "following_url": "https://api.github.com/users/larrifax/following{/other_user}",
            "gists_url": "https://api.github.com/users/larrifax/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/larrifax/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/larrifax/subscriptions",
            "organizations_url": "https://api.github.com/users/larrifax/orgs",
            "repos_url": "https://api.github.com/users/larrifax/repos",
            "events_url": "https://api.github.com/users/larrifax/events{/privacy}",
            "received_events_url": "https://api.github.com/users/larrifax/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-03T14:33:25Z"
        },
        {
          "id": 40144138,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDE0NDEzOA==",
          "user": {
            "login": "klevinlaughs",
            "id": 13974016,
            "node_id": "MDQ6VXNlcjEzOTc0MDE2",
            "avatar_url": "https://avatars.githubusercontent.com/u/13974016?u=2622a063c7a65b0f41976fe29ebb6e79aa83d48c&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/klevinlaughs",
            "html_url": "https://github.com/klevinlaughs",
            "followers_url": "https://api.github.com/users/klevinlaughs/followers",
            "following_url": "https://api.github.com/users/klevinlaughs/following{/other_user}",
            "gists_url": "https://api.github.com/users/klevinlaughs/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/klevinlaughs/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/klevinlaughs/subscriptions",
            "organizations_url": "https://api.github.com/users/klevinlaughs/orgs",
            "repos_url": "https://api.github.com/users/klevinlaughs/repos",
            "events_url": "https://api.github.com/users/klevinlaughs/events{/privacy}",
            "received_events_url": "https://api.github.com/users/klevinlaughs/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-04T06:25:05Z"
        },
        {
          "id": 40146196,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDE0NjE5Ng==",
          "user": {
            "login": "alfaproject",
            "id": 60164,
            "node_id": "MDQ6VXNlcjYwMTY0",
            "avatar_url": "https://avatars.githubusercontent.com/u/60164?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/alfaproject",
            "html_url": "https://github.com/alfaproject",
            "followers_url": "https://api.github.com/users/alfaproject/followers",
            "following_url": "https://api.github.com/users/alfaproject/following{/other_user}",
            "gists_url": "https://api.github.com/users/alfaproject/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/alfaproject/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/alfaproject/subscriptions",
            "organizations_url": "https://api.github.com/users/alfaproject/orgs",
            "repos_url": "https://api.github.com/users/alfaproject/repos",
            "events_url": "https://api.github.com/users/alfaproject/events{/privacy}",
            "received_events_url": "https://api.github.com/users/alfaproject/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-04T07:05:59Z"
        },
        {
          "id": 40268395,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDI2ODM5NQ==",
          "user": {
            "login": "jimbuck",
            "id": 2332163,
            "node_id": "MDQ6VXNlcjIzMzIxNjM=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2332163?u=efaed6b3f7d2b871432b485a44fdc1c2721a9b62&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jimbuck",
            "html_url": "https://github.com/jimbuck",
            "followers_url": "https://api.github.com/users/jimbuck/followers",
            "following_url": "https://api.github.com/users/jimbuck/following{/other_user}",
            "gists_url": "https://api.github.com/users/jimbuck/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jimbuck/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jimbuck/subscriptions",
            "organizations_url": "https://api.github.com/users/jimbuck/orgs",
            "repos_url": "https://api.github.com/users/jimbuck/repos",
            "events_url": "https://api.github.com/users/jimbuck/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jimbuck/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-05T16:29:50Z"
        },
        {
          "id": 40372163,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDM3MjE2Mw==",
          "user": {
            "login": "FDIM",
            "id": 1985429,
            "node_id": "MDQ6VXNlcjE5ODU0Mjk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1985429?u=4ea4afbdda02611e40568913a64e483428c9c9f1&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/FDIM",
            "html_url": "https://github.com/FDIM",
            "followers_url": "https://api.github.com/users/FDIM/followers",
            "following_url": "https://api.github.com/users/FDIM/following{/other_user}",
            "gists_url": "https://api.github.com/users/FDIM/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/FDIM/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/FDIM/subscriptions",
            "organizations_url": "https://api.github.com/users/FDIM/orgs",
            "repos_url": "https://api.github.com/users/FDIM/repos",
            "events_url": "https://api.github.com/users/FDIM/events{/privacy}",
            "received_events_url": "https://api.github.com/users/FDIM/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-08T13:59:49Z"
        },
        {
          "id": 40372448,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDM3MjQ0OA==",
          "user": {
            "login": "eugenotop",
            "id": 29663871,
            "node_id": "MDQ6VXNlcjI5NjYzODcx",
            "avatar_url": "https://avatars.githubusercontent.com/u/29663871?u=4bb89eac09035c99c9e5689ebf39134256e0407e&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/eugenotop",
            "html_url": "https://github.com/eugenotop",
            "followers_url": "https://api.github.com/users/eugenotop/followers",
            "following_url": "https://api.github.com/users/eugenotop/following{/other_user}",
            "gists_url": "https://api.github.com/users/eugenotop/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/eugenotop/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/eugenotop/subscriptions",
            "organizations_url": "https://api.github.com/users/eugenotop/orgs",
            "repos_url": "https://api.github.com/users/eugenotop/repos",
            "events_url": "https://api.github.com/users/eugenotop/events{/privacy}",
            "received_events_url": "https://api.github.com/users/eugenotop/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-08T14:03:20Z"
        },
        {
          "id": 40372955,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDM3Mjk1NQ==",
          "user": {
            "login": "lecollage",
            "id": 12492168,
            "node_id": "MDQ6VXNlcjEyNDkyMTY4",
            "avatar_url": "https://avatars.githubusercontent.com/u/12492168?u=0512a2faa11a2cd0ec157bce1887f931be1bda23&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/lecollage",
            "html_url": "https://github.com/lecollage",
            "followers_url": "https://api.github.com/users/lecollage/followers",
            "following_url": "https://api.github.com/users/lecollage/following{/other_user}",
            "gists_url": "https://api.github.com/users/lecollage/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/lecollage/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/lecollage/subscriptions",
            "organizations_url": "https://api.github.com/users/lecollage/orgs",
            "repos_url": "https://api.github.com/users/lecollage/repos",
            "events_url": "https://api.github.com/users/lecollage/events{/privacy}",
            "received_events_url": "https://api.github.com/users/lecollage/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-08T14:08:57Z"
        },
        {
          "id": 40373087,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDM3MzA4Nw==",
          "user": {
            "login": "mokeev1995",
            "id": 8450876,
            "node_id": "MDQ6VXNlcjg0NTA4NzY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/8450876?u=f44e1f55b0066e6c8f307b3a613c9b0b39af6343&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/mokeev1995",
            "html_url": "https://github.com/mokeev1995",
            "followers_url": "https://api.github.com/users/mokeev1995/followers",
            "following_url": "https://api.github.com/users/mokeev1995/following{/other_user}",
            "gists_url": "https://api.github.com/users/mokeev1995/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/mokeev1995/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/mokeev1995/subscriptions",
            "organizations_url": "https://api.github.com/users/mokeev1995/orgs",
            "repos_url": "https://api.github.com/users/mokeev1995/repos",
            "events_url": "https://api.github.com/users/mokeev1995/events{/privacy}",
            "received_events_url": "https://api.github.com/users/mokeev1995/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-08T14:10:33Z"
        },
        {
          "id": 40373114,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDM3MzExNA==",
          "user": {
            "login": "thekiba",
            "id": 1910515,
            "node_id": "MDQ6VXNlcjE5MTA1MTU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1910515?u=877cd312db7e01cb4a15a9be6858c906674daf44&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/thekiba",
            "html_url": "https://github.com/thekiba",
            "followers_url": "https://api.github.com/users/thekiba/followers",
            "following_url": "https://api.github.com/users/thekiba/following{/other_user}",
            "gists_url": "https://api.github.com/users/thekiba/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/thekiba/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/thekiba/subscriptions",
            "organizations_url": "https://api.github.com/users/thekiba/orgs",
            "repos_url": "https://api.github.com/users/thekiba/repos",
            "events_url": "https://api.github.com/users/thekiba/events{/privacy}",
            "received_events_url": "https://api.github.com/users/thekiba/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-08T14:10:49Z"
        },
        {
          "id": 40373820,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDM3MzgyMA==",
          "user": {
            "login": "ifrntnd",
            "id": 41643887,
            "node_id": "MDQ6VXNlcjQxNjQzODg3",
            "avatar_url": "https://avatars.githubusercontent.com/u/41643887?u=6b55e84e13f22d998ede84eccb02af8c7d2db1a0&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ifrntnd",
            "html_url": "https://github.com/ifrntnd",
            "followers_url": "https://api.github.com/users/ifrntnd/followers",
            "following_url": "https://api.github.com/users/ifrntnd/following{/other_user}",
            "gists_url": "https://api.github.com/users/ifrntnd/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ifrntnd/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ifrntnd/subscriptions",
            "organizations_url": "https://api.github.com/users/ifrntnd/orgs",
            "repos_url": "https://api.github.com/users/ifrntnd/repos",
            "events_url": "https://api.github.com/users/ifrntnd/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ifrntnd/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-08T14:19:17Z"
        },
        {
          "id": 40374298,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDM3NDI5OA==",
          "user": {
            "login": "dkopitsa",
            "id": 778892,
            "node_id": "MDQ6VXNlcjc3ODg5Mg==",
            "avatar_url": "https://avatars.githubusercontent.com/u/778892?u=03ebdd9692405ea76b740215e8644107d992a6d2&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/dkopitsa",
            "html_url": "https://github.com/dkopitsa",
            "followers_url": "https://api.github.com/users/dkopitsa/followers",
            "following_url": "https://api.github.com/users/dkopitsa/following{/other_user}",
            "gists_url": "https://api.github.com/users/dkopitsa/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/dkopitsa/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/dkopitsa/subscriptions",
            "organizations_url": "https://api.github.com/users/dkopitsa/orgs",
            "repos_url": "https://api.github.com/users/dkopitsa/repos",
            "events_url": "https://api.github.com/users/dkopitsa/events{/privacy}",
            "received_events_url": "https://api.github.com/users/dkopitsa/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-08T14:23:59Z"
        },
        {
          "id": 40377983,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDM3Nzk4Mw==",
          "user": {
            "login": "ln-e",
            "id": 2379195,
            "node_id": "MDQ6VXNlcjIzNzkxOTU=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2379195?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ln-e",
            "html_url": "https://github.com/ln-e",
            "followers_url": "https://api.github.com/users/ln-e/followers",
            "following_url": "https://api.github.com/users/ln-e/following{/other_user}",
            "gists_url": "https://api.github.com/users/ln-e/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ln-e/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ln-e/subscriptions",
            "organizations_url": "https://api.github.com/users/ln-e/orgs",
            "repos_url": "https://api.github.com/users/ln-e/repos",
            "events_url": "https://api.github.com/users/ln-e/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ln-e/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-08T15:01:17Z"
        },
        {
          "id": 40515192,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDUxNTE5Mg==",
          "user": {
            "login": "grzesiek110",
            "id": 34006751,
            "node_id": "MDQ6VXNlcjM0MDA2NzUx",
            "avatar_url": "https://avatars.githubusercontent.com/u/34006751?u=5d95e965efcb0bb6eca534f8eb6082b8bf893f79&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/grzesiek110",
            "html_url": "https://github.com/grzesiek110",
            "followers_url": "https://api.github.com/users/grzesiek110/followers",
            "following_url": "https://api.github.com/users/grzesiek110/following{/other_user}",
            "gists_url": "https://api.github.com/users/grzesiek110/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/grzesiek110/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/grzesiek110/subscriptions",
            "organizations_url": "https://api.github.com/users/grzesiek110/orgs",
            "repos_url": "https://api.github.com/users/grzesiek110/repos",
            "events_url": "https://api.github.com/users/grzesiek110/events{/privacy}",
            "received_events_url": "https://api.github.com/users/grzesiek110/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-10T06:55:13Z"
        },
        {
          "id": 40515319,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDUxNTMxOQ==",
          "user": {
            "login": "marezo",
            "id": 20990609,
            "node_id": "MDQ6VXNlcjIwOTkwNjA5",
            "avatar_url": "https://avatars.githubusercontent.com/u/20990609?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/marezo",
            "html_url": "https://github.com/marezo",
            "followers_url": "https://api.github.com/users/marezo/followers",
            "following_url": "https://api.github.com/users/marezo/following{/other_user}",
            "gists_url": "https://api.github.com/users/marezo/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/marezo/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/marezo/subscriptions",
            "organizations_url": "https://api.github.com/users/marezo/orgs",
            "repos_url": "https://api.github.com/users/marezo/repos",
            "events_url": "https://api.github.com/users/marezo/events{/privacy}",
            "received_events_url": "https://api.github.com/users/marezo/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-10T06:57:27Z"
        },
        {
          "id": 40515589,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDUxNTU4OQ==",
          "user": {
            "login": "qazah",
            "id": 6519162,
            "node_id": "MDQ6VXNlcjY1MTkxNjI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/6519162?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/qazah",
            "html_url": "https://github.com/qazah",
            "followers_url": "https://api.github.com/users/qazah/followers",
            "following_url": "https://api.github.com/users/qazah/following{/other_user}",
            "gists_url": "https://api.github.com/users/qazah/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/qazah/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/qazah/subscriptions",
            "organizations_url": "https://api.github.com/users/qazah/orgs",
            "repos_url": "https://api.github.com/users/qazah/repos",
            "events_url": "https://api.github.com/users/qazah/events{/privacy}",
            "received_events_url": "https://api.github.com/users/qazah/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-10T07:02:10Z"
        },
        {
          "id": 40515841,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDUxNTg0MQ==",
          "user": {
            "login": "tyroux",
            "id": 13907007,
            "node_id": "MDQ6VXNlcjEzOTA3MDA3",
            "avatar_url": "https://avatars.githubusercontent.com/u/13907007?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/tyroux",
            "html_url": "https://github.com/tyroux",
            "followers_url": "https://api.github.com/users/tyroux/followers",
            "following_url": "https://api.github.com/users/tyroux/following{/other_user}",
            "gists_url": "https://api.github.com/users/tyroux/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/tyroux/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tyroux/subscriptions",
            "organizations_url": "https://api.github.com/users/tyroux/orgs",
            "repos_url": "https://api.github.com/users/tyroux/repos",
            "events_url": "https://api.github.com/users/tyroux/events{/privacy}",
            "received_events_url": "https://api.github.com/users/tyroux/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-10T07:06:33Z"
        },
        {
          "id": 40677813,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDY3NzgxMw==",
          "user": {
            "login": "snsakib",
            "id": 37431397,
            "node_id": "MDQ6VXNlcjM3NDMxMzk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/37431397?u=cd3495b6b57626c780f4965d97e894f5d0533631&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/snsakib",
            "html_url": "https://github.com/snsakib",
            "followers_url": "https://api.github.com/users/snsakib/followers",
            "following_url": "https://api.github.com/users/snsakib/following{/other_user}",
            "gists_url": "https://api.github.com/users/snsakib/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/snsakib/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/snsakib/subscriptions",
            "organizations_url": "https://api.github.com/users/snsakib/orgs",
            "repos_url": "https://api.github.com/users/snsakib/repos",
            "events_url": "https://api.github.com/users/snsakib/events{/privacy}",
            "received_events_url": "https://api.github.com/users/snsakib/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-12T04:20:58Z"
        },
        {
          "id": 40742850,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDc0Mjg1MA==",
          "user": {
            "login": "bossqone",
            "id": 71897,
            "node_id": "MDQ6VXNlcjcxODk3",
            "avatar_url": "https://avatars.githubusercontent.com/u/71897?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/bossqone",
            "html_url": "https://github.com/bossqone",
            "followers_url": "https://api.github.com/users/bossqone/followers",
            "following_url": "https://api.github.com/users/bossqone/following{/other_user}",
            "gists_url": "https://api.github.com/users/bossqone/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/bossqone/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/bossqone/subscriptions",
            "organizations_url": "https://api.github.com/users/bossqone/orgs",
            "repos_url": "https://api.github.com/users/bossqone/repos",
            "events_url": "https://api.github.com/users/bossqone/events{/privacy}",
            "received_events_url": "https://api.github.com/users/bossqone/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-12T22:32:30Z"
        },
        {
          "id": 40842777,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MDg0Mjc3Nw==",
          "user": {
            "login": "ryanmcafee",
            "id": 2336262,
            "node_id": "MDQ6VXNlcjIzMzYyNjI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2336262?u=b28cc3659dc77e36ea2fe4b0586a03ad0be11948&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/ryanmcafee",
            "html_url": "https://github.com/ryanmcafee",
            "followers_url": "https://api.github.com/users/ryanmcafee/followers",
            "following_url": "https://api.github.com/users/ryanmcafee/following{/other_user}",
            "gists_url": "https://api.github.com/users/ryanmcafee/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/ryanmcafee/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/ryanmcafee/subscriptions",
            "organizations_url": "https://api.github.com/users/ryanmcafee/orgs",
            "repos_url": "https://api.github.com/users/ryanmcafee/repos",
            "events_url": "https://api.github.com/users/ryanmcafee/events{/privacy}",
            "received_events_url": "https://api.github.com/users/ryanmcafee/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-15T18:18:37Z"
        },
        {
          "id": 41387600,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MTM4NzYwMA==",
          "user": {
            "login": "jovankrunic",
            "id": 11611830,
            "node_id": "MDQ6VXNlcjExNjExODMw",
            "avatar_url": "https://avatars.githubusercontent.com/u/11611830?u=d2846890dc1599dba4ff3328582043c344191ffb&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/jovankrunic",
            "html_url": "https://github.com/jovankrunic",
            "followers_url": "https://api.github.com/users/jovankrunic/followers",
            "following_url": "https://api.github.com/users/jovankrunic/following{/other_user}",
            "gists_url": "https://api.github.com/users/jovankrunic/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/jovankrunic/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/jovankrunic/subscriptions",
            "organizations_url": "https://api.github.com/users/jovankrunic/orgs",
            "repos_url": "https://api.github.com/users/jovankrunic/repos",
            "events_url": "https://api.github.com/users/jovankrunic/events{/privacy}",
            "received_events_url": "https://api.github.com/users/jovankrunic/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-24T12:42:21Z"
        },
        {
          "id": 41715331,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MTcxNTMzMQ==",
          "user": {
            "login": "banjankri",
            "id": 2622286,
            "node_id": "MDQ6VXNlcjI2MjIyODY=",
            "avatar_url": "https://avatars.githubusercontent.com/u/2622286?u=c306e149337441a93d6fd8fd201aa31253887ae8&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/banjankri",
            "html_url": "https://github.com/banjankri",
            "followers_url": "https://api.github.com/users/banjankri/followers",
            "following_url": "https://api.github.com/users/banjankri/following{/other_user}",
            "gists_url": "https://api.github.com/users/banjankri/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/banjankri/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/banjankri/subscriptions",
            "organizations_url": "https://api.github.com/users/banjankri/orgs",
            "repos_url": "https://api.github.com/users/banjankri/repos",
            "events_url": "https://api.github.com/users/banjankri/events{/privacy}",
            "received_events_url": "https://api.github.com/users/banjankri/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-04-30T06:11:43Z"
        },
        {
          "id": 41985174,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MTk4NTE3NA==",
          "user": {
            "login": "Borzilov",
            "id": 15954932,
            "node_id": "MDQ6VXNlcjE1OTU0OTMy",
            "avatar_url": "https://avatars.githubusercontent.com/u/15954932?u=dbd1cbe40b5fbbb0c6f56af6fdc00095105ac4e6&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/Borzilov",
            "html_url": "https://github.com/Borzilov",
            "followers_url": "https://api.github.com/users/Borzilov/followers",
            "following_url": "https://api.github.com/users/Borzilov/following{/other_user}",
            "gists_url": "https://api.github.com/users/Borzilov/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/Borzilov/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/Borzilov/subscriptions",
            "organizations_url": "https://api.github.com/users/Borzilov/orgs",
            "repos_url": "https://api.github.com/users/Borzilov/repos",
            "events_url": "https://api.github.com/users/Borzilov/events{/privacy}",
            "received_events_url": "https://api.github.com/users/Borzilov/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-05-04T12:21:39Z"
        },
        {
          "id": 42381624,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MjM4MTYyNA==",
          "user": {
            "login": "codecoster",
            "id": 5447022,
            "node_id": "MDQ6VXNlcjU0NDcwMjI=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5447022?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/codecoster",
            "html_url": "https://github.com/codecoster",
            "followers_url": "https://api.github.com/users/codecoster/followers",
            "following_url": "https://api.github.com/users/codecoster/following{/other_user}",
            "gists_url": "https://api.github.com/users/codecoster/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/codecoster/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/codecoster/subscriptions",
            "organizations_url": "https://api.github.com/users/codecoster/orgs",
            "repos_url": "https://api.github.com/users/codecoster/repos",
            "events_url": "https://api.github.com/users/codecoster/events{/privacy}",
            "received_events_url": "https://api.github.com/users/codecoster/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-05-10T14:17:07Z"
        },
        {
          "id": 42884445,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240Mjg4NDQ0NQ==",
          "user": {
            "login": "MartinJohns",
            "id": 5269069,
            "node_id": "MDQ6VXNlcjUyNjkwNjk=",
            "avatar_url": "https://avatars.githubusercontent.com/u/5269069?u=9316c074a591f8ced9eed6007edf8d73924509c2&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MartinJohns",
            "html_url": "https://github.com/MartinJohns",
            "followers_url": "https://api.github.com/users/MartinJohns/followers",
            "following_url": "https://api.github.com/users/MartinJohns/following{/other_user}",
            "gists_url": "https://api.github.com/users/MartinJohns/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MartinJohns/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MartinJohns/subscriptions",
            "organizations_url": "https://api.github.com/users/MartinJohns/orgs",
            "repos_url": "https://api.github.com/users/MartinJohns/repos",
            "events_url": "https://api.github.com/users/MartinJohns/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MartinJohns/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-05-18T13:54:10Z"
        },
        {
          "id": 43328192,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MzMyODE5Mg==",
          "user": {
            "login": "patrickmichalina",
            "id": 6701211,
            "node_id": "MDQ6VXNlcjY3MDEyMTE=",
            "avatar_url": "https://avatars.githubusercontent.com/u/6701211?v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/patrickmichalina",
            "html_url": "https://github.com/patrickmichalina",
            "followers_url": "https://api.github.com/users/patrickmichalina/followers",
            "following_url": "https://api.github.com/users/patrickmichalina/following{/other_user}",
            "gists_url": "https://api.github.com/users/patrickmichalina/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/patrickmichalina/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/patrickmichalina/subscriptions",
            "organizations_url": "https://api.github.com/users/patrickmichalina/orgs",
            "repos_url": "https://api.github.com/users/patrickmichalina/repos",
            "events_url": "https://api.github.com/users/patrickmichalina/events{/privacy}",
            "received_events_url": "https://api.github.com/users/patrickmichalina/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-05-25T03:23:44Z"
        },
        {
          "id": 43568563,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MzU2ODU2Mw==",
          "user": {
            "login": "tomardern",
            "id": 1135454,
            "node_id": "MDQ6VXNlcjExMzU0NTQ=",
            "avatar_url": "https://avatars.githubusercontent.com/u/1135454?u=c29ecdaa3ec515fae90865e3bd416dab7185087e&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/tomardern",
            "html_url": "https://github.com/tomardern",
            "followers_url": "https://api.github.com/users/tomardern/followers",
            "following_url": "https://api.github.com/users/tomardern/following{/other_user}",
            "gists_url": "https://api.github.com/users/tomardern/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/tomardern/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/tomardern/subscriptions",
            "organizations_url": "https://api.github.com/users/tomardern/orgs",
            "repos_url": "https://api.github.com/users/tomardern/repos",
            "events_url": "https://api.github.com/users/tomardern/events{/privacy}",
            "received_events_url": "https://api.github.com/users/tomardern/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-05-29T16:06:21Z"
        },
        {
          "id": 43608164,
          "node_id": "MDEzOklzc3VlUmVhY3Rpb240MzYwODE2NA==",
          "user": {
            "login": "MarcosMeli",
            "id": 446796,
            "node_id": "MDQ6VXNlcjQ0Njc5Ng==",
            "avatar_url": "https://avatars.githubusercontent.com/u/446796?u=f936acf09fdde690c4a56ce62f9152b51eeae03b&v=4",
            "gravatar_id": "",
            "url": "https://api.github.com/users/MarcosMeli",
            "html_url": "https://github.com/MarcosMeli",
            "followers_url": "https://api.github.com/users/MarcosMeli/followers",
            "following_url": "https://api.github.com/users/MarcosMeli/following{/other_user}",
            "gists_url": "https://api.github.com/users/MarcosMeli/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/MarcosMeli/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/MarcosMeli/subscriptions",
            "organizations_url": "https://api.github.com/users/MarcosMeli/orgs",
            "repos_url": "https://api.github.com/users/MarcosMeli/repos",
            "events_url": "https://api.github.com/users/MarcosMeli/events{/privacy}",
            "received_events_url": "https://api.github.com/users/MarcosMeli/received_events",
            "type": "User",
            "site_admin": false
          },
          "content": "+1",
          "created_at": "2019-05-30T03:25:29Z"
        }
      ]